### ISSUE TITLE
[feature request] serial port support

### ISSUE THREAD

**Issue by t184256** [Limine-Bootloader/Limine#155]
I've tried using limine for my distro and it works fine, but I don't get anything on the serial port as with the other bootloaders. I can only wait until the timeout expires and boots the default entry.

Is controlling limine through a serial port a planned feature?

**Comment by Mintsuki** [comment]
Yeah this is actually a planned feature that I was coincidentally working on at the moment. It will very likely be upstreamed shortly.

**Comment by t184256** [comment]
Can confirm that 2.86 serial works and looks fabulous.

Backspace didn't work with QEMU's -nographic, but it works with QEMU serial in QEMU GUI, so it might be something on my end.
