### ISSUE TITLE
Is there a demo iso that I can boot and see it run?

### ISSUE THREAD

**Issue by lonnietc** [Limine-Bootloader/Limine#157]
Hello,

I am new to bootloaders and am working on a new kernel project that builds a x86_64 elf kernel.

I really did not want to use GRUB and wanted to find something new and came a cross your Limine project that seems like it will boot elf images.

Is there a simple demo ISO that I can download and see it in action before I dig into the coding?

**Comment by Mintsuki** [comment]
You can find an example at https://github.com/stivale/stivale2-barebones

**Comment by lonnietc** [comment]
Thanks and I will look into it
