### ISSUE TITLE
[Feature Request] Support other filesystems.

### ISSUE THREAD

**Issue by uni-dos** [Limine-Bootloader/Limine#159]
Do you have plans to support btrfs and f2fs?

**Comment by StaticSaga** [comment]
There are no plans currently as far as I'm aware. On UEFI you don't need filesystem drivers as you can just load the kernel and initrd in the EFI system partition. On BIOS systems you can have a separate /boot partition under a supported file system (ext* or FAT generally).

**Comment by Mintsuki** [comment]
Not really in the pipeline, but if someone is willing to PR support for an extra FS that's always welcome. Other than that doing what @StaticSaga said works.
