### ISSUE TITLE
Limine doesn't print anything to console even with -nographic

### ISSUE THREAD

**Issue by ethindp** [Limine-Bootloader/Limine#161]
**Limine version used**
Commit bcc72e3, UEFI

**Expected behaviour**
When running qemu with -nographic, I should see Limines output.

**Actual (broken) behaviour**
I don't see any output until my kernel boots.

**To Reproduce**
1. Boot kernel with qemu options `-serial stdio -nographic`. No limine output should be seen (even though the display *also* points at stdio).

**Stacktrace**
No stack trace.

**Additional context**
Also routing serial port output through stdio but this theoretically shouldn't matter.

**Comment by Mintsuki** [comment]
You need `SERIAL=yes` in the config in order to enable serial output.

**Comment by ethindp** [comment]
Thanks!
