### ISSUE TITLE
Limine does not start on Pentium III class computers

### ISSUE THREAD

**Issue by seriocomedy** [Limine-Bootloader/Limine#163]
**Limine version used**
2.88 BIOS MBR

**Expected behaviour**
Limine boot menu.

**Actual (broken) behaviour**
Limine does not start from IDE (PATA) HDD

**To Reproduce**
Start Limine on a Dell Latitude C600.

**Stacktrace**
limine.sys build ID mismatch
PANIC: Failed to load stage 3
Stacktrace:
  [0xdaff] <panic+0x86>
  [0xe159] <entry+0x7c>

**Additional context**
Computer is Dell Latitude C600 with 512MB RAM. Same disk image when written to newer computers boots fine. Issue only appears on this old computer. Build ID check is first time memcmp is called. Is asm memcmp implementation the culprit?

**Comment by Mintsuki** [comment]
May have to do with `jecxz`

**Comment by Mintsuki** [comment]
If you can, try replacing that with a `test ecx, ecx; jz` instead.

**Comment by Mintsuki** [comment]
Actually, triple checking this, it doesn't seem like any of the instructions shouldn't work on a PIII.

Have you made sure the image is properly made to begin with? It could just be that the limine.sys it is trying to load is just not the correct one.

**Comment by seriocomedy** [comment]
Starting reimaging onto the hard drive, will reply with the result when it finishes.

**Comment by seriocomedy** [comment]
Yeah drive was corrupted. Limine works now.
