### ISSUE TITLE
Page fault after new Page Table

### ISSUE THREAD

**Issue by enderice2** [Limine-Bootloader/Limine#166]
**Limine version used**
v3.0 BIOS and UEFI

**Expected behaviour**
After updating cr3 everything should work and no page fault should occur.

**Actual (broken) behaviour**
After new cr3 function returns but when a new function is called I get page fault at any address with the error `e=0003` (Reserved bit exception?) 
Tested on VMware and qemu, BIOS and UEFI. Same problem.

**To Reproduce**
Write a new Page Table level 4 in the cr3 register using Stivale2 protocol (I didn't test with Limine or other ones)

**Additional context**
[Video of the problem](https://youtu.be/t3RCxzS8cIY).

**Comment by StaticSaga** [comment]
After Limine loads your kernel it does not do anything anymore, so it looks like a bug in your VMM.

**Comment by enderice2** [comment]
Hmm... Probably but, I can't understand how only on 3.0 do I have this issue. Clearly, there's something about my code or the Limine.
This is how I set up the page table: https://github.com/EnderIce2/FennixProject/tree/main/kernel/src/mem

**Comment by Mintsuki** [comment]
Not a Limine bug.
