### ISSUE TITLE
Is the boot drive always number 1?

### ISSUE THREAD

**Issue by bkauler** [Limine-Bootloader/Limine#190]
This is not a bug report. It is a question how Limine numbers drives.

I got my ancient Acer Aspire laptop out of the closet. I bought this circa 2005, and it has a 32-bit CPU. One internal hard drive, mbr, and it has grub4dos installed, so comes up with a menu to choose a couple of installations of Linux, or Windows XP.

I booted the EasyOS usb-stick, with this extra menu entry:

```
:Internal drive
   PROTOCOL=chainload
   DRIVE=1
```

Because I thought that the internal drive would be number 1. However, I had to change to DRIVE=2 to get the grub4dos menu.

So does that mean the boot drive is always number 1?

**Comment by Mintsuki** [comment]
No, not necessarily. But it is not Limine that decides the order, it's the BIOS itself.
Often BIOSes will make the boot drive the "C:" drive (or more technically drive index `0x80` in a legacy BIOS), but this does not have to always be the case.

It is generally a bit safer to avoid using drive indexes whenever at all possible, and opting to use UUIDs, `boot://`, or labels instead, as they are more resilient to BIOSes randomly assigning different indexes to different drives.

That said... I am aware the legacy BIOS chainloading protocol does not offer an alternative to hardcoding a drive index. We could try to figure out an alternative way to specify a drive, like MBR IDs/GPT GUIDs or similar for the BIOS chainloading protocol, but this is not there right now.

**Comment by bkauler** [comment]
Yes, /dev/sdb has a mbr:

```
# lsblk --pairs -o PTUUID --nodeps /dev/sdb
PTUUID="c5e0f2d2"
```

That's a partition table uuid for the mbr drive.
That looks like a possibility, instead of a DRIVE number

**Comment by Mintsuki** [comment]
Yeah, this sounds good. I will implement this.
