### ISSUE TITLE
EFI chainload enhancement request

### ISSUE THREAD

**Issue by bkauler** [Limine-Bootloader/Limine#191]
Currently, the format is this:

```
:Internal drive
   PROTOCOL=chainload
   IMAGE_PATH=guid://${PARTUUID}/path-to-efi
```

Would it be possible to leave off the "path to efi", so the uefi will do its own search for a efi?

**Comment by bkauler** [comment]
By "drive-uuid" I mean a uuid that identifies the drive, not a partition, like this:

```
# gdisk -l /dev/nvme1n1
 ...
Disk identifier (GUID): 494D4539-FF62-4BB1-B06B-86CC0BCB8B14
```
And also get it from lsblk:

# lsblk --pairs -o PTUUID --nodeps /dev/nvme1n1
PTUUID="494d4539-ff62-4bb1-b06b-86cc0bcb8b14"

And I think that is more correct, with lower-case letters.

**Comment by bkauler** [comment]
My thinking was a bit confused when I first posted this question!
Maybe its a dumb question anyway. We know from uefi docs what order it looks for a .efi file, so could put a path-to-efi in there, no need to leave it off the uri.

So I'll ask a different question. If a Linux OS is on a USB-stick, and you want to have a Limine menu that is generic. You might want a menu entry to chainload to the next esp partition, which would be on the internal drive.

I'm not sure, but I vaguely recall grub has something like that? "chainload +1" or something like that?

Hope that's not another dumb question.

**Comment by Mintsuki** [comment]
Well having such a chainloading option is really outside of the scope of how Limine is meant to operate.

That said, it would be possible, and it is something I meant to implement for a while, for both UEFI and BIOS to have a "return to firmware"/"boot next drive" option, which would work in a similar way as described, without having to special case a chainload path or anything like that.

**Comment by bkauler** [comment]
Another related question. It is ok to chainload modern Windows, like this:

```
:Windows (drive nvme1n1)
    PROTOCOL=chainload
    IMAGE_PATH=guid://67c45f63-8668-4fbd-9aa9-341a6dae89b4/EFI/Microsoft/Boot/bootmgfw.efi

```
However, Windows XP requires running an executable 'ntldr', and I cannot see how Limine can do that. Running "file ntldr" shows it to be "DOS executable (COM)".

Also, I think that Windows 7 requires running a different executable, 'bootmgr'

There are lots of people still using Win7, so maybe something worthwhile supporting.

**Comment by Mintsuki** [comment]
Windows XP does not support UEFI as far as I am aware. NTLDR is a BIOS loader so it'd only work with BIOS chainloading.

As for Windows 7, I know it supports UEFI in a limited way, but that kind of goes outside the scope of this issue.
