### ISSUE TITLE
Limine should show name and version on boot selection screen

### ISSUE THREAD

**Issue by zrudyt** [Limine-Bootloader/Limine#192]
You have built a great utility, so why not proudly advertize it?  I think Limine and the version number should show somewhere on oeither the top or bottom blank area on the screen,

**Comment by Mintsuki** [comment]
Hm, well, it does?

**Comment by Mintsuki** [comment]
Oh and by the way thanks for the compliments, appreciated!

**Comment by zrudyt** [comment]
Sorry, my post wasn't clear because I forgot a word ;-)  "I  think Limine and the version number should **ALWAYS** show ...".  If I set INTERFACE_BRANDING, the name and version disappears.

The compliment is well deserved.  I've been using limine since Barry K mentioned it on hos Puppy blog. I even wrote a quick and dirty script to complie limine-deploy on linux and use it to update my USB stick, then copy limine.sys.  No typing or manual intervention.

**Comment by Mintsuki** [comment]
Ah, I understand now. Well, I like to give people the option to customise what shows in the menu's title, even if it means not showing "Limine" and the version.

As for crediting, in the console (which should be always accessible whenever the menu is) you can show version and copyrighting information.

**Comment by zrudyt** [comment]
Thanks.  I've used the console before to get the version. Warning: one man's biased peersonal opinion follows:

i still think talented develpers who make the effort to build useful quality software and give it away for free deserve recognition.  By allowing others to hide your brand, you cannot get recognized.  Maybe a small unobtrusive limine version xxx in the bottom right corner if the user sets INTERFACE_BRANDING

At the end of day, your software, your rules, so I'll shut up now :)  Thanks again for your efforts!

**Comment by Mintsuki** [comment]
Yeah I get what you mean but there would undoubtedly be people who wouldn't be happy with that decision; plus people can still fork/patch the branding away in source code themselves.

I am personally fine with attribution and copyright being accessible from the unintrusive console, so it's not a big deal for me.

Thanks for all the kind words once again, though.
