### ISSUE TITLE
Panic on v3.11 - boots OK on v3.10.5 (Dell Latitude E7250)

### ISSUE THREAD

**Issue by zrudyt** [Limine-Bootloader/Limine#194]
I see a PANIC: Double Fault on boot with v3.11 - stack trace is attached.  v3.10.5 booted fine on this computer.  I always install the same way from the binary package, compile and run limine-deploy on linux, then copy limine.sys.  I boot from USB stick /dev/sdb1
![IMG_0501](https://user-images.githubusercontent.com/108995273/178276775-1e6a971a-b15e-43a0-870a-bf7423a9bbda.jpg)

**Comment by Mintsuki** [comment]
If I were to guess I'd say it's related to 77616a0. Though I'm not sure how it would cause this issue, the commit seems pretty harmless.

Given it's not an essential change, I will revert it on 3.0-branch, for now.

**Comment by Mintsuki** [comment]
Try 3.11.1

**Comment by zrudyt** [comment]
Let me know if you want me to do some testing or need any further info.

**Comment by zrudyt** [comment]
3.11.1 boots fine - thanks for the quick turnaround.  Let me know if you need me to do some testing for you to help narrow down the root cause

**Comment by Mintsuki** [comment]
Thanks for the help offer! I will let you know by mentioning you if I need some help.

Closing this for now as this is no longer an issue.
