### ISSUE TITLE
Feature request undo limine-deploy to gpt

### ISSUE THREAD

**Issue by bkauler** [Limine-Bootloader/Limine#197]
Had a coding marathon last night and wrote the rest of the Limine Installer. have to test it, will announce details and a package soon.

I have explained in the installer, how installation can be reverted, but legacy-bios installation to the gpt cannot, as I understand it, be reverted.

With limine-deploy to a mbr, the installer makes a backup copy of the mbr, and it is explained to the user how this can be restored.

Is it possible to do the same for the gpt?
I don't know anything about the structure of the gpt, though I do know there are two of them, a fallback gpt at the physical end of the drive, which I presume will be an extra complication.
If it isn't practical to do, I will just say in the installer that it isn't reversible.

**Comment by Mintsuki** [comment]
Just reverting the 512 byte MBR is dangerous as bootloader code is often stored in the 32K post-MBR gap.

And it goes without saying that the GPT embedding that Limine performs works differently.

So I cooked up a way to practically unwind all the changes made by `limine-deploy` and restore whatever data was touched by the Limine deployment process.

This is *not* perfect, for example changes made to partitions after the deploy may be unwantingly unwound by the undeploy procedure.

I may add a way to detect changes made post-deploy by the user and have the undeploy procedure warn the user to make this safer.

**Comment by bkauler** [comment]
Thanks for taking that on.

The installer can warn the user about partition changes breaking undeploy. 

Here are first photos of the Installer:

https://bkhome.org/news/202207/first-test-of-limine-installer.html

**Comment by Mintsuki** [comment]
That looks nice!

By the way, how come you say Limine cannot chainload Windows from a different partition? That should be doable if it chainloads the VBR with something like:
```
DRIVE=2
PARTITION=1
```
(Assuming partition 1 contains the Windows boot code)

...that said, I did just notice that setting `MBR_ID=` will actually ignore the `PARTITION=` value, so there's a bug to fix.

**Comment by bkauler** [comment]
> By the way, how come you say Limine cannot chainload Windows from a different partition? That should be doable if it chainloads the VBR with something like:

No, I stated the opposite. If there is only one drive, hence one mbr, and one boot partition.
limine-deploy will have written to that mbr, and hence it cannot chainload Windows.
Limine cannot directly execute the ntldr or bootmgr of Windows XP or 7.
At least that is my understanding.

**Comment by Mintsuki** [comment]
The VBR contains Windows's boot code, it typically resides at the start of a partition, it's not the MBR.

I was suggesting chainloading something like:
```
MBR_ID=12345678
PARTITION=3
```
Assuming the Windows VBR boot code is installed on partition 3 of the drive with MBR ID 0x12345678

**Comment by bkauler** [comment]
Does the MBR_ID need to be prefixed with "0x" for hex?

**Comment by Mintsuki** [comment]
No, I made a typo sorry. Fixed.

**Comment by bkauler** [comment]
That's pretty good then. I didn't realise that you could specify the partition number as well, so Limine will chainload the VBR of the partition. Yes, very good!
