### ISSUE TITLE
Does limine support btrfs and luks2?

### ISSUE THREAD

**Issue by ghost** [Limine-Bootloader/Limine#202]
Sorry for using the bug report form for this but I couldn't find any info on this in the repository. I am guessing the answer is no to both?

**Comment by ilobilo** [comment]
yeah it doesn't support them
https://github.com/limine-bootloader/limine#supported-filesystems

**Comment by Mintsuki** [comment]
I am going to answer with a link to #159.

Generally speaking support for all possible filesystems in the bootloader is both not feasible and redundant, as for EFI you need a separate ESP partition which can also house the Linux kernel and initrd, thus removing the need for extra filesystem support in the bootloader entirely. Avoids bloat.
