### ISSUE TITLE
Limine 3.16 crash on USB 2.0 port

### ISSUE THREAD

**Issue by Reynaldo333** [Limine-Bootloader/Limine#209]
Limine 3.16
Fujitsu FUTRO MA574

Has an issue on USB port 2.0. It won`t boot and displays:
> Limine 3.16
> Config file not found
> For information on the format of Limine config entries,consult CONFIG.md in
> the root of the Limine source repository.
> 
> Press a key to enter Limine console...

USB stick will not boot also on USB 3.0 port and unmountable after that.

It has been a week that I am using USB 3.0 on the latest 64-bit Easy OS without any issues.

**For the 32-bit Easy OS, no issues on USB 2.0 and USB 3.0 ports.**

**Comment by Mintsuki** [comment]
This bug frankly escapes my understanding, assuming it really is a bug to begin with.

Could you try doing the same with the ISO I sent to you on the other issue and seeing if it behaves the same?

**Comment by Reynaldo333** [comment]
Yes, it behaves the same.

**Comment by Mintsuki** [comment]
Can you please try with the latest Limine version? I'll close this issue for now, but feel free to reopen it if it is still not fixed or post here if you have any progress to share!

**Comment by Reynaldo333** [comment]
Ok...Thanks!

Noong Miy, Set 21, 2022 nang 6:24 AM, sinulat ni mint <
***@***.***> ang:

**Comment by Reynaldo333** [comment]
This is what I`m getting booting in USB 2.0 port on the test ISO you`ve
sent to me.
[image: DSC_0013.JPG]

after pressing F10 in the editor console...
[image: DSC_0014.JPG]

Best regards,
Reynaldo

Noong Miy, Ago 24, 2022 nang 1:31 PM, sinulat ni mint <
***@***.***> ang:

**Comment by Andy-Python-Programmer** [comment]
@Reynaldo333 The images are not actually attached in the comment you sent above.
