### ISSUE TITLE
Limine OOMs when loading a large module on fragmented memory maps

### ISSUE THREAD

**Issue by rdmsr** [Limine-Bootloader/Limine#211]
**Limine version used**
3.17.3 (Running Lyre)

**Expected behaviour**
The module being loaded without any error

**Actual (broken) behaviour**
The bootloader panics with a "High memory allocator error: Out of Memory" when loading the module.

**To Reproduce**
1. Get a PC with over 48 memory map entries and 8gb of RAM
2. Flash lyre's latest nightly iso
3. Boot

**Stacktrace**
```
  [0xb283] <panic+0x9c>
  [0x9aa8] <ext_mem_alloc_type_aligned+0xe8>
  [0x9b08] <ext_mem_alloc_type+0x16>
  then freadall, get_file, limine_load, boot and _menu
``` 
  
**Thoughts**
This issue may be caused by the fact that the memory map is so fragmented that the module can't be loaded in one contiguous chunk. This could probably be fixed by allowing non-contiguous loading of kernel modules in `freadall`.

**Comment by Mintsuki** [comment]
As discussed on Discord, this is mainly caused by the machine in question having too little sub-4GiB contiguous RAM to load the module.
