### ISSUE TITLE
Does the bootloader support the XFS filesystem?

### ISSUE THREAD

**Issue by ghost** [Limine-Bootloader/Limine#212]
seeing the README.md there seems to be no support for the XFS filesystem? is it safe to assume it does not work on XFS filesystems?

**Comment by Mintsuki** [comment]
No, it does not directly support XFS, but quoting the README:
> Even though these are the filesystems Limine supports directly, *any* filesystem can be utilised by the kernel provided that the kernel (and any needed modules) are on a directly supported filesystem.
