### ISSUE TITLE
protocol: add UART MMIO address tag

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [Limine-Bootloader/Limine#215]
The limine protocol should provide UART MMIO address tag; parsing the DTB just for UART is annoying and usually its better to have it before parsing it for better debugging experience.

**Comment by Itay2805** [comment]
sounds a bit redundant given that the terminal exists, and can provide the same debugging functionality in a cross-platform way

**Comment by 48cf** [comment]
> sounds a bit redundant given that the terminal exists, and can provide the same debugging functionality in a cross-platform way

You won't be able to easily retain the contents of the terminal after the machine reboots though, which is why serial is superior

**Comment by Itay2805** [comment]
Wouldn't it be better to just add support for serial on the terminal tag? The main thing about this is that it provides a unified debug output interface, and the bootloader will handle adding support for whatever needed unrelated to the arch board or platform.
