### ISSUE TITLE
Feature request: Change the main location of the config file for UEFI

### ISSUE THREAD

**Issue by j0534ng31** [Limine-Bootloader/Limine#219]
## Limine version used

Latest 3 and 4 versions, from **UEFI**.

## Expected behaviour

- The first place to search for the `limine.cfg` file should be the same as the limine `.efi` file location, dinamically obtained and not limited to `boot:///EFI/limine` directory or `BOOTX64.EFI` filename.

- To be able to use many directories with the same or different limine versions in the **ESP** partition, each one with his own config.

- To be able to use many **ESP** partitions in the same disk, each one with his own limine and config.

- The current hardcoded locations are ok to me as an extra, even when I don't fully understand them (once limine will be able to search in its own executable directory).

## Actual behaviour

- Limine `.efi` scans blindly for the first config file on every partition of the boot drive, ignoring the most logical place to search for it: its own location.

- Cannot create an **independent** UEFI boot entry of limine, configured without menu (timeout=0), to boot an OS instantly.

- Cannot create an **independent** configuration of limine in a secondary ESP partition.

- Can create an **independent** configuration of limine in a secondary drive, but only one, with the same limits previously explained.

## Example

1. Imagine that the main UEFI boot manager is `limine` or `rEFInd`, or even none (you use the predefined computer specific hotkey to select the desired boot entry).

2. One of the entries is '**limine boot manager**': It should read a global config, preferable but not limited in its own directory, offering to boot every configured OS (no matter in what partition or disk).

3. A second entry is any Linux distro that had adopted limine as boot manager, such as '**EasyOS**': It should be able to read a different config, necessarily in its own directory, to boot that OS instantly.

   - As I understand after testing, that is not possible because limine is going to use the same global config file, offering every other OS installed.

4. Booting limine from a second ESP partition of the same disk drive the behaviour is worse, as its limine configuration is completely ignored: Limine is going to use the global config file found in first ESP partition.

5. And finally, booting a second disk drive with its own ESP partition, the behaviour should be the same of the points 2 and 3.

**Comment by Mintsuki** [comment]
The above is as far as I am willing to go. This way Limine prioritises the partition on which the image is to find its config.

If that fails, behaviour falls back to what it was before.

The reason for this is that the behaviour of the EFI port of Limine should mirror the BIOS port as close as possible, and on BIOS doing this is not possible since BIOS does not boot files off partitions.

This change will allow you to do what you want, as long as each Limine is in its own partition (ESP or otherwise).
