### ISSUE TITLE
Menu does not display on SanDisk Ultra USB stick

### ISSUE THREAD

**Issue by bkauler** [Limine-Bootloader/Limine#220]
As #218 is closed, perhaps better to start a new issue. See the last posts in that issue.

**Comment by bkauler** [comment]
Oh, dear, I have had this problem without realising it, as always booted the USB-sticks with TIMEOUT=0

I have tested with a SanDisk Extreme USB3 stick, same problem...

With 3.21 and TIMEOUT=10, for both UEFI and legacy boot just get a blank screen until timeout then Easy boots.

With 4.1.2 and TIMEOUT=10, for UEFI get the little bar, legacy get a flashing cursor, until timeout then boots.

**Comment by Mintsuki** [comment]
You have `QUIET=yes` set.

**Comment by bkauler** [comment]
Ha ha, yes, sorry for troubling you, it works now.
