### ISSUE TITLE
How to debug a NULL response to a request

### ISSUE THREAD

**Issue by linkdd** [Limine-Bootloader/Limine#221]
**Limine version used**

4.1.3-binary using BIOS (via QEMU)

**Expected behaviour**

```c
#include <limine.h>

// ...

static volatile struct limine_module_request mod_req = {
  .id = LIMINE_MODULE_REQUEST,
  .revision = 0
};

// ...

void kmain(void) {
  // ...
  assert(mod_req.response != NULL, "should not be null");
  // ...
}
```

**Actual (broken) behaviour**

The response to a module request is `NULL`.

**Comment by Andy-Python-Programmer** [comment]
What's your limine configuration (`limine.cfg`).

**Comment by linkdd** [comment]
```
DEFAULT_ENTRY=1
TIMEOUT=0

:MyOS
  PROTOCOL=limine
  KERNEL_PATH=boot:///boot/kernel.bin

  MODULE_PATH=boot:///sys/modules/capabilities.bin
```

I'm also using xorriso to build an ISO image containing the necessary files.

Other requests works as expected (Terminal, Kernel File, Bootloader Info, Memory Map Info)

**Comment by Mintsuki** [comment]
Your `assert()` macro is either non-standard, or your call to it involves the use of a comma operator which makes the macro call useless. In either case more information is required about your `assert()`.

**Comment by linkdd** [comment]
It was just a minimal example, the actual code is:

```c
  if (module_request.response != NULL) {
    printk("Module list:\n");

    for (size_t module_idx = 0; module_idx < module_request.response->module_count; module_idx++) {
      struct limine_file *module = module_request.response->modules[module_idx];

      printk("# %s %s\n", module->path, module->cmdline);
    }
  }
```

Nothing gets printed, hence: `module_request.response` is NULL...

Also, my assert function (not a macro) works just fine everywhere else in my code. Bold to assume the bug comes from here and that I did not try other methods to ensure the value was indeed NULL.

**Comment by Mintsuki** [comment]
Give a buildable, reproducible example. Also curb your tone.

**Comment by linkdd** [comment]
I was only asking if Limine guarantees that this value is never NULL (which means the problem is obviously on my end).

I made a barebones example but it is unable to reproduce the error unless I remove the `MODULE_PATH` from the config file.

I'm closing the issue for now.

**Comment by Mintsuki** [comment]
Any response can be NULL if the bootloader does not provide it, and you should should be checking for that. Yes.

W.r.t. your specific issue, I have never seen Limine fail to provide a modules response if a module is properly found and loaded, which leads me to believe this issue is on your end, unless you can produce a reproducible example. If you can do so, feel free to reopen the issue and we'll look into that :)

**Comment by Andy-Python-Programmer** [comment]
The module response **can** be NULL if there are no modules requested (this is done to save memory required to allocate the response). In your case, module was specified so, it's an issue on your end.
