### ISSUE TITLE
Boot protocol not specified!

### ISSUE THREAD

**Issue by AviseOffical** [Limine-Bootloader/Limine#229]
i tested out the new update v4.20221007.0 but got an error

![a](https://user-images.githubusercontent.com/113899383/194637843-c34f6c5f-7f78-4484-8e0f-7a547ec59525.PNG)

Code:

mkdir -p iso/boot/limine
	cp $(KERNEL_TARGET) iso/boot
	cp limine/limine.sys limine/limine-cd.bin iso/boot/limine
	echo 'TIMEOUT = 3' 						> iso/boot/limine/limine.cfg
	echo ''                					>> iso/boot/limine/limine.cfg
	echo ':$(OS_NAME)'           		    >> iso/boot/limine/limine.cfg
	echo ''                					>> iso/boot/limine/limine.cfg
	echo 'PROTOCOL = multiboot2'			>> iso/boot/limine/limine.cfg
	echo 'KERNEL_CMDLINE = hello'					>> iso/boot/limine/limine.cfg
	echo 'KERNEL_PATH = boot:///kernel.bin'	>> iso/boot/limine/limine.cfg
	xorriso -as mkisofs -b boot/limine/limine-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table --protective-msdos-label iso -o $(IMAGE_TARGET)

$(KERNEL_TARGET) = kernel.bin
$(OS_NAME) = os name
$(IMAGE_TARGET) = kernel.iso

**Comment by Mintsuki** [comment]
You need to remove the spaces around the `=`
