### ISSUE TITLE
wtf happened?!

### ISSUE THREAD

**Issue by AviseOffical** [Limine-Bootloader/Limine#230]
none of my projects that uses limine does work!

![s](https://user-images.githubusercontent.com/113899383/194644965-d8fbe30a-8bfd-488c-b60b-59c95193d59a.PNG)

trying to use kernel.bin file

using multiboot2

**Comment by lukflug** [comment]
quality issue

**Comment by AviseOffical** [comment]
quality issue?

**Comment by Mintsuki** [comment]
I think this is what we call, in technical jargon, an issue of skill

**Comment by Dennisbonke** [comment]
Seems to be an old version and you're providing exactly zero information for us to determine what is going on. Could you please provide relevant information, like version information and such?

**Comment by AviseOffical** [comment]
mkdir -p iso
	cp $(KERNEL_TARGET) limine/limine.sys limine/limine-cd.bin iso/
	echo 'TIMEOUT=3' 						> iso/limine.cfg
	echo ''                					>> iso/limine.cfg
	echo ':$(OS_NAME)'           		    >> iso/limine.cfg
	echo ''                					>> iso/limine.cfg
	echo 'PROTOCOL=multiboot2'			>> iso/limine.cfg
	echo 'CMDLINE=hello'					>> iso/limine.cfg
	echo 'KERNEL_PATH=boot:///kernel.bin'	>> iso/limine.cfg
	xorriso -as mkisofs -b limine-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table --protective-msdos-label iso -o $(IMAGE_TARGET)

**Comment by lukflug** [comment]
"quality issue" as in the quality of this GitHub issue

**Comment by Dennisbonke** [comment]
Still no version information or anything remotely useful, try again later.

**Comment by AviseOffical** [comment]
i have tryed every version it used to work on like 3.0, currently trying to get it to work on v4.0

**Comment by Dennisbonke** [comment]
> i have tryed every version it used to work on like 3.0, currently trying to get it to work on v4.0

You got an exact number of that version tho?

**Comment by AviseOffical** [comment]
v3.0-binary and v4.20221007.0-binary

**Comment by Dennisbonke** [comment]
The screenshot is from v4.20221007.0?

**Comment by AviseOffical** [comment]
no v3.0, i get the same on v4 to

**Comment by lukflug** [comment]
dubious

**Comment by Dennisbonke** [comment]
> no v3.0, i get the same on v4 to

Doubt, autodetection isn't in v4.

**Comment by AviseOffical** [comment]
kinda weird it used to work last week no problem

**Comment by Dennisbonke** [comment]
Was last week on v3.0 by any chance?

**Comment by Dennisbonke** [comment]
Also can you be more specific about the 3.0 version?

**Comment by AviseOffical** [comment]
its just v0.3-binary in branch

:edit
v3.0-branch-binary

**Comment by Dennisbonke** [comment]
Latest commit in that branch?

**Comment by AviseOffical** [comment]
yes

**Comment by Dennisbonke** [comment]
X to doubt, as the latest 3.0 binary doesn't have autodetection

**Comment by lukflug** [comment]
x

**Comment by AviseOffical** [comment]
i dont know i just auto download limine v3.0-binary

git clone https://github.com/limine-bootloader/limine -b v3.0-binary --depth=1
make -c limine

**Comment by Dennisbonke** [comment]
yeah that's not the branch, you're using 3.0 exactly which is old as hell. Newer versions don't do autodetect anymore. Issue of skill, update to newer versions.

**Comment by AviseOffical** [comment]
i fucking tryed and it does not work!

**Comment by Dennisbonke** [comment]
Yeah but you gave 0 information as to why it doesn't work. Even your screenshot is outdated as fuck. Thanks for playing, try again later.

**Comment by lukflug** [comment]
v3.0-branch-binary?

**Comment by Andy-Python-Programmer** [comment]
> i dont know i just auto download limine v3.0-binary
> 
> git clone https://github.com/limine-bootloader/limine -b v3.0-binary --depth=1
> make -c limine


```
cd limine
git log
```
