### ISSUE TITLE
unpacked kernel file size

### ISSUE THREAD

**Issue by CorruptedByCPU** [Limine-Bootloader/Limine#232]
Hey!

Its good to know where is the "unpacked" kernel from ELF file, but it would be nice to know also what size (Bytes) of space it takes, wouldn't it?

_*** Nice to have. ***_

Documentation:
![image](https://user-images.githubusercontent.com/53617677/198848384-800ab3b1-d5cf-47c5-916e-5d3c376f3846.png)

**Comment by 48cf** [comment]
You should map code and data with different permissions, I think adding a `size` field to that would only discourage that since you could map everything with same permissions instead. Just place some symbols around .text, .data and .rodata sections and map everything with the right permissions.

**Comment by CorruptedByCPU** [comment]
That's a good point.
