### ISSUE TITLE
README confusing about filesystems

### ISSUE THREAD

**Issue by stacksmith** [Limine-Bootloader/Limine#237]
`Even though these are the filesystems Limine supports directly, any filesystem can be utilised by the kernel provided that the kernel (and any needed modules) are on a directly supported filesystem.`

I think what you are saying is that the kernel must reside on a supported filesystem and may implement and use any other filesystem types(or anything else for that matter).

But I am not sure.

Maybe you are saying that the kernel must reside on a supported system, but once booted, can magically use unsupported filesystems?  Huh.  What would that mean?

Maybe it is best to remove the paragraph as it really says absolutely nothing.  If the reader is not aware that they can write a kernel and filesystem drivers, this paragraph is not helpful.  Your target audience should know this anyway.

**Comment by 48cf** [comment]
Yeah it is kind of confusing for someone who's not very technical, I suggest we change this paragraph to "Limine can load it's configuration, the kernel and modules from any of the filesystems listed above" or something alike.

**Comment by stacksmith** [comment]
That is much better!
