### ISSUE TITLE
PANIC while loading kernel

### ISSUE THREAD

**Issue by Abdulhadi5692HDI2** [Limine-Bootloader/Limine#242]
**Limine version used**
I used version: 4.20221204.0.
I'm using UEFI and BIOS.

**Expected behaviour**
A running kernel with paging enabled.

**Actual (broken) behaviour**
A limine PANIC came up with a conflict.

**To Reproduce**
1. Boot the ISO
2. Select my OS from the menu
3. Error screen

**Stacktrace**
![dddi](https://user-images.githubusercontent.com/110974220/206925382-280ce2d6-081c-40d1-9e5f-c66f70f72439.png)

**Additional Stuff**
I'm using this [tutorial](https://wiki.osdev.org/Setting_Up_Paging)  from osdev wiki!

**Comment by Mintsuki** [comment]
Hi,
You define Limine request in a header (https://github.com/Abdulhadi5692HDI2/MilkyOS/blob/50ed8f2653b382974b1559ab1f2922303cb66d42/include/kernel.h#L6 , which also lacks include guards) which is going to be included in more than one .c file thus leading to the shown panic over duplicated requests.

This is not a bug, it is an issue with your kernel.

**Comment by Abdulhadi5692HDI2** [comment]
Thanks.
