### ISSUE TITLE
riscv support

### ISSUE THREAD

**Issue by bindsdev** [Limine-Bootloader/Limine#249]
Are there any plans or have there been any discussions to add RISC-V support? I believe it would be beneficial to add support for it as it seems like it is gaining some traction and will be relevant in the future.

**Comment by Mintsuki** [comment]
RISC-V/UEFI support is planned.

**Comment by Mintsuki** [comment]
As a quick update, RISC-V support is being actively worked on by @xvanc and a few others :)

**Comment by blanham** [comment]
🔜

**Comment by hvrsim** [comment]
@bindsdev  riscv support is merged now, so this issue should be closed

**Comment by Mintsuki** [comment]
Support merged in trunk.
