### ISSUE TITLE
Chainloading truncates CMDLINE

### ISSUE THREAD

**Issue by sad-goldfish** [Limine-Bootloader/Limine#254]
Chainloading truncates CMDLINE (original 430 characters) for Linux Kernel. Booting with Linux protocol does not do this. Not sure if this is expected or not. I think rEFIND chainloads but still preserves the CMDLINE.

**Comment by sad-goldfish** [comment]
Using [v4.20230307.0](https://github.com/limine-bootloader/limine/releases/tag/v4.20230307.0).

**Comment by Mintsuki** [comment]
Truncated to how many characters? What is the expected line and the truncated line?

**Comment by Mintsuki** [comment]
Should be fixed in 4.20230308.0
