### ISSUE TITLE
UEFI boot issue (aarch64)

### ISSUE THREAD

**Issue by ghost** [Limine-Bootloader/Limine#255]
![Screenshot from 2023-03-11 12-58-12](https://user-images.githubusercontent.com/127256142/224511502-22361da5-38a2-43a8-8607-e09ceeeb1c44.png)
I'm not sure if this is just user error on my part. I was only ever able to get this to work one time on the aarch64 platform, but since then I haven't had any luck. I was hoping this latest update would of fixed it in case this was a bug

**Comment by ghost** [comment]
It seems I was able to resolve this by cloning the repo and building the project manually. The prebuilt binaries seem to be bad somehow

**Comment by Mintsuki** [comment]
I cannot reproduce this on the latest binary release. Are you sure you're using the `v4.x-branch-binary` branch and not `v4.0-binary` by any chance?
