### ISSUE TITLE
module not loading

### ISSUE THREAD

**Issue by leecannon** [Limine-Bootloader/Limine#258]
I have been getting the below error recently, the module path in the config file is `boot://2/boot/kernel.map` but limine tries to load `boot://2/boot`.

![image](https://user-images.githubusercontent.com/2286349/227622774-2b1b4bb9-5799-4dda-99fc-7298d232bcfd.png)

limine.cfg
```
:olympus
    PROTOCOL=limine
    KERNEL_PATH=boot://2/boot/zeus

    MODULE_PATH=boot://2/boot/kernel.map
    MODULE_CMDLINE=kernel-map
```

**Comment by Mintsuki** [comment]
Please try 4.20230325.0

**Comment by leecannon** [comment]
Fixed.
