### ISSUE TITLE
LIMINE_MEMMAP_BOOTLOADER_RECLAIMABLE memory region and limine terminal request

### ISSUE THREAD

**Issue by braindigitalis** [Limine-Bootloader/Limine#259]
If the kernel requests a [LIMINE_TERMINAL_REQUEST](https://github.com/limine-bootloader/limine/blob/trunk/PROTOCOL.md#terminal-feature), then the memory area flagged in the memory map as `LIMINE_MEMMAP_BOOTLOADER_RECLAIMABLE` is technically *not* reclaimable.

Attempting to reclaim this memory will (rather obviously) corrupt the place where the write() function lives, so any attempt to write to the terminal will crash the OS.

I propose a simple fix to prevent anyone making this mistake; if the kernel has requested a terminal, then instead of `LIMINE_MEMMAP_BOOTLOADER_RECLAIMABLE` this memory should be reported as `LIMINE_MEMMAP_KERNEL_AND_MODULES` (i couldn't think of any more fitting existing value) or potentially a new memory type: `LIMINE_MEMMAP_BOOTLOADER_ACTIVE` (or whatever works).

Please let me know your thoughts.

**Comment by DeanoBurrito** [comment]
Part of the requirements for using the terminal is not reclaiming that memory, see the sections in the spec under the each architecture:

`Bootloader-reclaimable memory entries are left untouched until after the kernel is done utilising bootloader-provided facilities (this terminal being one of them).`
