### ISSUE TITLE
Limine Crashes on startup by just holding any key

### ISSUE THREAD

**Issue by Nokodev-programming** [Limine-Bootloader/Limine#266]
To trigger the crash. Start the os and right before the limine bootloader ends and the os kick's in. Hold any key. This will result to a crash (CPU will go shutdown state)

Original Issue located at https://github.com/CosmosOS/Cosmos/issues/2651

**Comment by Mintsuki** [comment]
Hello, thanks for the report.

Unfortunately, I cannot reproduce this issue. Can you be more specific regarding the steps to reproduce the problem?

**Comment by Nokodev-programming** [comment]
When you boot a os with limine. When seeing the limine bootloader's screen, hold any key and it will crash

Video of demostration (Don't ask about the wallpaper background as thats a joke wallpaper)
https://streamable.com/0v6r3h

**Comment by Mintsuki** [comment]
I still cannot reproduce. Make sure that you are using the latest Limine version and try again and let me know.

**Comment by Nokodev-programming** [comment]
Im using Limine from COSMOS. I currently don't know what version of Limine they are using. (Also i am using someone's elso operating system) I am not sure if limine has fixed this or not. I will try to send another video with the keyboard inputs im sending. Maybe will that help out.

**Comment by Mintsuki** [comment]
I doubt it is going to be helpful. Tell upstream to update the Limine version to latest.

**Comment by Nokodev-programming** [comment]
It seems like VMPlayer will prevent any onscreen keyboard software from detecting keys. What i do know is cosmos started using limine this year. The seccond month of 2023. So maybe the latest version of limine of that date.

**Comment by Mintsuki** [comment]
Yes, which is definitely not the latest version. I know because I could see an issue from the video you sent that has been fixed semi-recently. Again, please tell Cosmos or the OS vendor/developer(s) to update Limine versions.

**Comment by Nokodev-programming** [comment]
It seems like that the entire server went inactive. I am not sure if they gonna response as in central europe time its less than a hour away from being night.
![image](https://user-images.githubusercontent.com/86970410/233807120-d20edeab-80e4-4c52-a253-9ccb41c4b3fe.png)

**Comment by Mintsuki** [comment]
Running `strings <Image file path here> | grep 'Limine 4\.2' | uniq` should show the version of Limine.

**Comment by Nokodev-programming** [comment]
Limine 4.20221216.0

**Comment by Mintsuki** [comment]
The latest version is 4.20230422.0 (actually released today).

**Comment by Nokodev-programming** [comment]
Let me check some diffirent iso's from the community to comfirm its Limine 4.20221216.0 and if its somewhere in the range. il close this issue and attempt to ask the cosmos devs to update to the latest version of limine

**Comment by Nokodev-programming** [comment]
It looks like the limine's version from cosmos is 4.20221216.0. Il go ask them and close this issue
