### ISSUE TITLE
Clarification on limine.cfg new line escaping

### ISSUE THREAD

**Issue by ghost** [Limine-Bootloader/Limine#272]
It is unclear in the documentation if it is possible to escape newlines with a `\` for the config. Sometimes the lines of options can get quite long so breaking them up for readability would be nice. If this is already supported then could it be added to the documentation of the config file?

**Comment by Mintsuki** [comment]
It is not possible. Generally speaking if something is not mentioned, then it is not a thing.

It may be supported in the future if I get around to it, and once it is, it will be added to the documentation :)
