### ISSUE TITLE
Problem with booting hybrid ISO image

### ISSUE THREAD

**Issue by h4ckee** [Limine-Bootloader/Limine#273]
Hi.
I'm trying to build hybrid ISO image using following command:
```
        xorriso -as mkisofs \
                -b boot/limine-cd.bin \
                -no-emul-boot \
                -boot-load-size 4 \
                -boot-info-table \
                --protective-msdos-label \
                -o image.iso
        limine-deploy image.iso
```
Here's what wipefs shows:
```
        wipefs image.iso
        DEVICE    OFFSET TYPE    UUID                   LABEL
        image.iso 0x8001 iso9660 2023-05-27-12-02-39-00
        image.iso 0x1fe  dos
```

While it successfully boots on VirtualBox as ISO image, I'm not able to boot off usb flash when I insert it on my laptop (which's configured to boot from Legacy BIOS).
Originally I tried this command with a bit different options:

```
	xorrisofs \
		-V $OSNAME \
		-A ${OSNAME}-${VERSION} \
		-quiet -N -D -l -r \
		-b boot/limine-cd.bin \
		-c boot/boot.cat \
		-hide-rr-moved \
		-no-emul-boot \
		-boot-load-size 4 \
		-boot-info-table \
		-o ${BUILD_DIR}/${OSNAME}-${VERSION}.iso
```
With no success.
Also tried to force-mbr:
`	limine-deploy ${BUILD_DIR}/${OSNAME}-${VERSION}.iso --force-mbr`
without any success. Maybe I have to use UEFI for correct work?
Is there a way to make a hybrid ISO but without UEFI?

Regards,
Sergey.

**Comment by Mintsuki** [comment]
Hello,

have you tried keeping the `--efi` flags as shown in the example? It doesn't really matter if you're going to use UEFI or not, but this will create a full hybrid ISO the "proper" way, capable of booting from both UEFI and BIOS and both as optical media and flash media.

**Comment by h4ckee** [comment]
no, but will try. ll'be back soon...

**Comment by h4ckee** [comment]
rebuilt image with limine-cd-efi.bin, but still no booting from usb. In BIOS set booting device in AUTO and UEFI mode only.
the commands:

```
	xorriso -as mkisofs \
		-b boot/limine-cd.bin \
		-no-emul-boot \
		-boot-load-size 4 \
		-boot-info-table \
		--efi-boot boot/limine-cd-efi.bin \
		-efi-boot-part --efi-boot-image \
		--protective-msdos-label \
		-o image.iso \
	isofs
	limine-deploy image.iso
```

Here's wipefs output:
```
> doas wipefs /dev/sdc
DEVICE OFFSET TYPE    UUID                   LABEL
sdc    0x8001 iso9660 2023-05-27-18-44-44-00 ISOIMAGE
sdc    0x200  gpt
sdc    0x1fe  PMBR
```
```
> doas mount /dev/sdc /mnt/usb/
mount: /mnt/usb: WARNING: source write-protected, mounted read-only.
> ll /mnt/usb/boot
total 13M
-rw-r--r-- 1 root root 7,2M мая 27 21:44 initramfs
-rw-r--r-- 1 root root 1,5M мая 27 20:55 limine-cd-efi.bin
-rw-r--r-- 1 root root  24K мая 27 20:55 limine-cd.bin
-rw-r--r-- 1 root root  367 мая 27 21:44 limine.cfg
-rw-r--r-- 1 root root 223K мая 27 20:55 limine.sys
-rw-r--r-- 1 root root 3,3M мая 27 12:24 vmlinuz
> lsblk -f /dev/sdc
NAME   FSTYPE  FSVER LABEL    UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
sdc    iso9660       ISOIMAGE 2023-05-27-18-44-44-00                     0   100% /mnt/usb
├─sdc1
├─sdc2 vfat    FAT12          59D9-C93B
└─sdc3

```

BTW, when I wrote Linux Mint to my USB flash, it booted without issues.

**Comment by h4ckee** [comment]
I can provide you the image if you like.

**Comment by Mintsuki** [comment]
Like this I'm not quite able to tell what is wrong. Sure, try sending the image. You can gz compress it if GitHub refuses to let you upload anything with different extensions.

**Comment by h4ckee** [comment]
I've uploaded it on Google Drive:
https://drive.google.com/file/d/1JOC2hxrQsgnR4YL3f2UlndVA9kow4Jrx/view?usp=sharing

**Comment by Mintsuki** [comment]
Okay, so from what I can gather from a quick look at your image, I assume you built Limine yourself. Did you enable the UEFI ports at `./configure` time? Because within the FAT12 EFI partition I fail to find any `.EFI` image. So that would be a starting point of where to look.

Of course that would make it fail to boot on UEFI.

As for BIOS, I can actually boot the image you sent with BIOS, as a HDD/USB stick, but not from optical media (CD). I assume this is a problem with the commands on your end still. Please let me know what it was if you manage to fix it.

**Comment by h4ckee** [comment]
I'll check your notes soon, thanx for feedback.

**Comment by h4ckee** [comment]
Hello.
USB UEFI BIOS Support option has been disabled on my Thinkpad. I thought that it disables only UEFI, but actually it affects all USB attached devices like diskettes, Optical drives and USB Sticks with also DOS partitions. I've rebuild my ISO in pure MBR mode and after enabling it I was able to boot successfuly from USB stick and from CD-RW.
Thanx for help!
