### ISSUE TITLE
Limine SMP response returns odd values on Thinkpad T400 

### ISSUE THREAD

**Issue by sigsegv7** [Limine-Bootloader/Limine#278]
![bug](https://github.com/limine-bootloader/limine/assets/130274810/ce910106-6d7e-4c64-b405-a9ad676fe987)

**Comment by sigsegv7** [comment]
on the off chance that I cannot be reached, contact `quinn@vegaa.systems` or `ian@vegaa.systems`

**Comment by Kaimakan71** [comment]
@sigsegv7 found this issue while I was working with him. At the bottom of the screenshot is a dump of the `limine_smp_response` struct.

**Comment by sigsegv7** [comment]
whoops
