### ISSUE TITLE
Add double-buffering on the default Limine framebuffer

### ISSUE THREAD

**Issue by raphm4044** [Limine-Bootloader/Limine#282]

**Comment by Mintsuki** [comment]
What is this supposed to mean??

**Comment by raphm4044** [comment]
I ask that because i tried inplementing it, and it resulted in a broken, slow thing

**Comment by Mintsuki** [comment]
How exactly is that Limine's issue?

**Comment by Andy-Python-Programmer** [comment]
skill issue smh
