### ISSUE TITLE
Latitude 6400 boot panic

### ISSUE THREAD

**Issue by zrudyt** [Limine-Bootloader/Limine#294]
v5.20230811.0 boot panics on a Dell Latitude E6400 booting in BIOS mode from a USB stick. The same stick boots fine on a Latitude E7250. The E6400 used to boot perfectly on v3 or v4 (can't remember which) but I haven't tried a USB boot with a more up to date version in months. Panic screen is attached - sorry for the horrible photo

![latitude_e6400_boot_panic](https://github.com/limine-bootloader/limine/assets/108995273/2fe681d7-e7c1-455d-9cd2-e78dfae6d0e7)

**Comment by Mintsuki** [comment]
Hi, thanks for the report!

Is this Limine as compiled on the binary branches, or is this from a distro/you built it yourself?

Also, is there a chance you can try different versions to pin point which version is the first to exhibit the issue?

**Comment by zrudyt** [comment]
Hi, I use your pre-built binaries.

After twelve (12) different tries, I finally found the version that broke the E6400 booting. v3.18.3 will show the boot selection menu and boot properly when an item is selected, and v3.19 panics just like all later versions I tried, including the latest.

Also, when booting with v3.18.3 and previous v3 versions, a brief message saying "WARNING: TOO MANY VOLUMES" flashes for less than a second before the boot menu appears. All my boot files are on my boot drive (sdb1), which only has that one partition

**Comment by Mintsuki** [comment]
Thanks for testing that, I appreciate.

Is the v3.19 panic the same as the one you get on the latest version? Stack trace and all?

**Comment by zrudyt** [comment]
Similar but different

![latitude_e6400_boot_panic_v3 19](https://github.com/limine-bootloader/limine/assets/108995273/9f6d4841-72e3-45ee-aba9-b1459dbf1d4e)

**Comment by Mintsuki** [comment]
[limine-test.tar.gz](https://github.com/limine-bootloader/limine/files/12340127/limine-test.tar.gz)
Can you try this and see if it works? Thanks.

**Comment by zrudyt** [comment]
Hey, thanks for the quick beta. Completely different error now, plus it won't boot on my E7250 either - same Stage 3 error. Contrary to the error displayed, limine-bios.sys is present in /boot on sdb1 (see second pic)

![latitude_e6400_boot_panic_test](https://github.com/limine-bootloader/limine/assets/108995273/a28f306f-2a1a-4bec-be90-f84cfe35551f)

![limine(2)](https://github.com/limine-bootloader/limine/assets/108995273/d4a08aa1-6e4c-407d-8140-143d4d72d434)

**Comment by Mintsuki** [comment]
Hi, sorry for the delay and thanks for testing the last build.

Can you try this one now?
[limine-test.tar.gz](https://github.com/limine-bootloader/limine/files/12366717/limine-test.tar.gz)

**Comment by zrudyt** [comment]
No worries on the delay. No rush from my side as the old v3 still works.

Both Dells still fail, but each one fails differently???

Dell E6400
![3 6400](https://github.com/limine-bootloader/limine/assets/108995273/e6b9c137-34cd-4ce6-8d4b-d0a25027c3d9)

Dell E7250

![3 7250](https://github.com/limine-bootloader/limine/assets/108995273/7ce07c58-57cc-408f-9ec6-6a6981ae7bbf)

**Comment by Mintsuki** [comment]
A 2 machines issue sounds more like possibly a broken setup and installation procedure than an actual issue caused by Limine itself, but we'll see...

Do you mind sharing in detail the procedure used to install Limine on an image/USB stick, and the procedure used to boot the USB stick?

**Comment by zrudyt** [comment]
Sorry, I just tried it again on a newly formatted USB stick and get both errors pictured above for each Dell, so it's not a broken install - the 2 laptops behave differently with your latest test code. I scripted the install to eliminate the chance for error (see below).

The script works perfectly when installing the latest release, so I know the script works and that limine.cfg is in the right place. There are no subdirs on this test stick - everything is in the root. There are only 4 files on the whole USB drive; limine-bios.sys, limine.cfg, an initrd and a vmlinuz

USB stick is formatted EXT2. Procedure to boot is standard Dell - insert USB, power on or reboot, hit F12 at the Dell screen, then select USB as the boot device.

```
#!/bin/sh -ev
mkdir -p '/tmp/limine'
tar xzf "$1" --directory='/tmp/limine' --strip-components=1
cd '/tmp/limine'
make
./limine bios-install /dev/sdb
mount /dev/sdb1 /mnt/sdb1
cp limine-bios.sys /mnt/sdb1
umount /dev/sdb1

```

**Comment by Mintsuki** [comment]
How many partitions does the USB stick contain? GPT or MBR? What about other disks on the same machine?

**Comment by zrudyt** [comment]
USB: MBR - 1 partition (linux)
E6400: MBR - 4 partitions (HPFS, linux, FreeBSD, NetBSD)
E7250: GPT - 4 partitions (EFI, Microsoft reserved, Microsoft basic data, Windows recovery)

Note that my USB key is a self-contained boot device and does not use any files off the local hard drive

**Comment by Mintsuki** [comment]
Have you tried a different USB stick?

**Comment by zrudyt** [comment]
Yes, 3 different USB sticks in fact, all name-brand units (i.e. no no-name low-quality sticks):

1. my original Issue was using a Sandisk Cruzer USB stick
2. your first limine-test was using a Verbatim USB stick
3. your second limine-test was using a newly formatted clean Kingston DataTraveler stick to ensure that there were no installation issues or conflicts with previous installations

**Comment by Mintsuki** [comment]
Can you try this one?
[limine-test.tar.gz](https://github.com/limine-bootloader/limine/files/12381194/limine-test.tar.gz)

**Comment by Mintsuki** [comment]
And please, report back as accurately as possible the behaviour that occurs.

**Comment by zrudyt** [comment]
Both computers still fail to boot. The two error screens are EXACTLY like the last two I posted - all rows and hex numbers are the same.

Behaviour details are simple. Inset USB, power on computer booting from USB, and the panic screen appears almost immediately. There is no discernable messages that quickly flash before the panic screen

Below is a detailed log of the installation, along with MD5 sums of all files which you can compare to yours.

```
md5sum Downloads/limine-test.tar.gz
-----------------------------------
50d08bbc6bf3ff4e7e4ac769d0b7de45  Downloads/limine-test.tar.gz

limine_test.sh Downloads/limine-test.tar.gz
-------------------------------------------
#!/bin/sh -ev
mkdir -p '/tmp/limine'
tar xzf "$1" --directory='/tmp/limine' --strip-components=1
cd '/tmp/limine'
make
cc -g -O2 -pipe -Wall -Wextra    -std=c99 limine.c  -o limine
./limine bios-install /dev/sdb
Physical block size of 512 bytes.
Installing to MBR.
Stage 2 to be located at 0x200 and 0x2800.
Reminder: Remember to copy the limine-bios.sys file in either
          the root, /boot, /limine, or /boot/limine directories of
          one of the partitions on the device, or boot will fail!
Limine BIOS stages installed successfully!
mount /dev/sdb1 /mnt/sdb1
cp limine-bios.sys /mnt/sdb1
umount /dev/sdb1

md5sum /mnt/sdb1/*
------------------
232d192a1e95151fbf2f53fae2114eaa  /mnt/sdb1/corepure64.gz
004954b5dbf954409dd4a092b14e452e  /mnt/sdb1/limine-bios.sys
764e1a4665cfde9e64c538c2ca69aa43  /mnt/sdb1/limine.cfg
md5sum: /mnt/sdb1/lost+found: Is a directory
04cb17bbf7fbca9aaaa2e1356a936d7c  /mnt/sdb1/vmlinuz64

ls -l /mnt/sdb1
----------------
total 19020
-r--r--r-- 1 root root 13439846 Aug 17 19:07 corepure64.gz
-rw-r--r-- 1 root root   196076 Aug 18 12:43 limine-bios.sys
-rw-r--r-- 1 root root      157 Aug 17 19:11 limine.cfg
drwx------ 2 root root    16384 Aug 17 18:56 lost+found/
-r--r--r-- 1 root root  5778048 Aug 17 19:07 vmlinuz64

```

**Comment by Mintsuki** [comment]
I just realised that you need to load files off ext2/3/4.

I kept giving you builds off `trunk` where ext2/3/4 support has been dropped when I should've been giving you builds off `v5.x`. Sorry.

Please try this build:
[limine-test.tar.gz](https://github.com/limine-bootloader/limine/files/12383173/limine-test.tar.gz)

**Comment by zrudyt** [comment]
Haha, I lost count of how many times I provided simplified test build to try to isolate a problem and over-simplified by deleting key features.

The good news is the Dell E7250 now boots fine, but the bad news is that the E6400 still panics. Same steps and hex codes in angle brackets  as before, but slightly different addresses in square brackets

![panic e6400](https://github.com/limine-bootloader/limine/assets/108995273/7276ad77-269d-4a28-82be-3c9586c5956d)

**Comment by Mintsuki** [comment]
Thank you, sorry about earlier.

Can you now try this one on the E6400?
[limine-test.tar.gz](https://github.com/limine-bootloader/limine/files/12383877/limine-test.tar.gz)

**Comment by zrudyt** [comment]
No worries. Lots of stuff scrolled off the screen that I can't see because the resolution on the E6400 is so low, but here's the last screen

![panic e6400](https://github.com/limine-bootloader/limine/assets/108995273/4d5909fa-29d6-44bd-a47f-a628cc67d2ee)

**Comment by Mintsuki** [comment]
Try this one now:
[limine-test.tar.gz](https://github.com/limine-bootloader/limine/files/12384542/limine-test.tar.gz)

**Comment by zrudyt** [comment]
Sorry - no success yet, but hopefully those extra trace prints are helping you narrow it down

![e6400](https://github.com/limine-bootloader/limine/assets/108995273/079ff6f3-c309-49a2-b8bb-d83172bc3c8b)

**Comment by Mintsuki** [comment]
Thank you. Yeah this was only meant as a test, not as a fix. Though this next one is supposed to fix, or work around, the issue.
[limine-test.tar.gz](https://github.com/limine-bootloader/limine/files/12385110/limine-test.tar.gz)

**Comment by zrudyt** [comment]
Success at last! The Dell E6400 boots perfectly with your latest fix.

I will test the E6400 again on your next release, and sporadically thereafter, but if ever you would like me to test a release candidate in the future, just ping me and I'll be glad to. I'll try to test some more old computers in the meantime.

Thanks for your diligence in chasing down this bug

**Comment by Mintsuki** [comment]
Thanks to you for helping me debug this!
