### ISSUE TITLE
Secure Boot with shim + key: Bootloader has not verified loaded image. System is compromised. Halting.

### ISSUE THREAD

**Issue by ghost** [Limine-Bootloader/Limine#298]
Hi there,

running limine on arch linux with shim + key and secure boot enabled I get that message.
EFI images and kernel are signed.

Any suggestion how can I prevent this?

**Comment by Mintsuki** [comment]
You can directly sign the Limine EFI executable (after using `limine enroll-config` on it) and add the key used to sign it to the firmware, instead of using `shim`. That should work.

**Comment by ghost** [comment]
This works fine. Thank you.

**Comment by Mintsuki** [comment]
Great!
