### ISSUE TITLE
Is it possible to name the efi entry?

### ISSUE THREAD

**Issue by Visone-Selektah** [Limine-Bootloader/Limine#300]
Hi!
I have a grub install on a void system with a specific name, and a venom linux system with limine, both efi systems. 
Right now I'm in the process of change grub for limine in the void system but both instances have the same name in the BIOS boot order. Is there any way to be able to assing a specific name for the limine efi entry?

**Comment by Mintsuki** [comment]
Hello! Have you looked at the `efibootmgr` utility? The Arch Linux wiki has a section about it here: https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface#efibootmgr

Feel free to reopen if there are further issues.
