### ISSUE TITLE
Add a warning of invalid entries in config file

### ISSUE THREAD

**Issue by janTatesa** [Limine-Bootloader/Limine#301]
I put the root uuid after : instead of //, and spent hours wondering why it doesnt work. Or spelled palette wrongly. So i think that liimine should warn you if it cannot parse the config.

**Comment by Andy-Python-Programmer** [comment]
>I put the root uuid after : instead of //, and spent hours wondering why it doesnt work. Or spelled palette wrongly. So i think that liimine should warn you if it cannot parse the config.

*limine :trollface:

**Comment by Mintsuki** [comment]
This feature won't be implemented.
