### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by ShalokShalom** [Limine-Bootloader/Limine#306]
Your design philosophy seems to make no remarks about btrfs and zfs snapshots. 

How do you expect me to boot into them, without providing support on the bootloader level?

**Comment by mobinmob** [comment]
> Your design philosophy seems to make no remarks about btrfs and zfs snapshots. 
> 
> How do you expect me to boot into them, without providing support on the bootloader level?

You can use snapshots with the initramfs. In that case the bootloader does not need to read the fs, just pass the relevant arguments to initramfs in the kernel commandline.
I am using zfs with zfsbootmenu, which can be loaded from limine/gumniboot/refind/syslinux, none of which support zfs directly.

**Comment by ShalokShalom** [comment]
Thanks a lot!

Could be worth including at the design philosophy page 😃
