### ISSUE TITLE
hibernation fails to resume

### ISSUE THREAD

**Issue by bound-variable** [Limine-Bootloader/Limine#307]
With grub, I could successfully hibernate via:
```
echo shutdown >| /sys/power/disk
echo disk >| /sys/power/state
```
But this doesn't work with limine. The system shuts down, but fails to resume. I'm using the linux protocol.

Limine 5.20230811.0
Gentoo

**Comment by Mintsuki** [comment]
Hello, thanks for the report.

Do you have any relevant log associated with the issue? Anything from `dmesg` that seems related to the problem?

Could you try the latest version (5.20230928.2) and see if that exhibits the problem as well?

**Comment by bound-variable** [comment]
Thanks for the prompt reply. I figured it out. The problem was with dracut:

https://bugzilla.redhat.com/show_bug.cgi?id=2060501
https://news.ycombinator.com/item?id=28644762
