### ISSUE TITLE
      KERNEL_PATH - The URI path of the kernel.

### ISSUE THREAD

**Issue by fungilife** [Limine-Bootloader/Limine#309]
an .elf file path a URI path ... 

Back in March 23 when I started packaging and offering limine I tried it and it worked (after a long hastle with guess work of making a working limine.cfg)  Now I have a user asking what is wrong and the nightmare of guesswork returns.

Anything I try on this 

    KERNEL_PATH=

is rejected

Why can't some examples of a general linux use can be offered to remove the guesswork of what MAY some of this tiny documentation mean by "terms".
Your site leads to download, no documentation, the git, and some social-media server that is can not and will not be accessed.  Is this where meaningful documentation is stored?  In a chatroom server?

I have done more than 20 upgrades of limine ... I believe I should be able to provide users with some guidance in making it work

**Comment by ElectrodeYT** [comment]
Consider reading [this](https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md)

Basically, if you want to read a elf file from the boot partition, its `boot:///path/to/elf/file`

**Comment by no92** [comment]
[There is documentation on this](https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md#uris). This documentation is referenced in the README and easily found in a clone, too. I don't know what the ranting is saying or trying to achieve.

**Comment by Mintsuki** [comment]
All the necessary documentation to write a working config file is provided in [here](https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md) as previously mentioned.

There is no such thing as a "general Linux use". It is all very distribution and setup dependent, and giving random magical instructions that will work everywhere is not possible.

Also quit ranting and acting so arrogantly. I can choose which platform I want to use to communicate with the community, and if you don't like it, don't use it, but don't come whining about it in GitHub issues (which by the way also work perfectly well to ask questions without acting like a prick).

That said, if you have an *actual* question, whether a valid bug or just asking for help with a non working configuration, ask said question. Because in this issue's message no question was asked, there was only whining.

**Comment by lukflug** [comment]
> Your site leads to download, no documentation, the git, and some social-media server that is can not and will not be accessed. Is this where meaningful documentation is stored? In a chatroom server?

The documentation *does* exist and *is part of* the Git repository.
The Discord server *can* be accessed and *is* accessed.
There's nearly 500 people there!

**Comment by fungilife** [comment]
> [There is documentation on this](https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md#uris). This documentation is referenced in the README and easily found in a clone, too. I don't know what the ranting is saying or trying to achieve.

The term "ranting" is a hostile term for telling another party that you don't make sense, and it would have been better to ask to explain what YOU don't understand.

**Comment by lukflug** [comment]
You were kinda being hostile in your original message. And "ranting" doesn't mean that the other party doesn't make sense. It's just that it's an unnecessarily lengthy diatribe.

**Comment by fungilife** [comment]
> All the necessary documentation to write a working config file is provided in [here](https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md) as previously mentioned.

obviously I have read the single page of documentation and it does not help.  I included the README file into the package back when it didn't come with any specific documentation.  Does it help?  NO!

> There is no such thing as a "general Linux use". It is all very distribution and setup dependent, and giving random magical instructions that will work everywhere is not possible.

I understand that you are writing this for various architectures but between them there is very little as reference to what the specific use differences may be.
For one, I don't know how well has this been adopted in android/Mac uses, I can only worry with x86.

Now, in all documents and talk I have encountered I have yet to see the use of boot:/// atered in any way, so why is it still there?  What else would it be?  

> That said, if you have an _actual_ question, whether a valid bug or just asking for help with a non working configuration, ask said question. Because in this issue's message no question was asked, there was only whining.

Yes there are 3 conclusions with limine, one must be a bootloading filesystem kernel expert to understand (if so) what is documented.
2  IF and ONLY IF  URI definition is researched and understood and used as so, then the "file.elf" must be something different than understood.
3  IF both conditions, 1 & 2 are correct, and the outcome of the specified tem is used correctly, and limine fails to boot, SOMETHING ELSE may be wrong.
8months ago, with the help of another user, I managed to see what I was doing wrong and got it right.  Now this right doesn't result to booting.  Same system starts with syslinux, grub, or lilo, but not with limine.

Why?  Because the documentation is insufficient to conclude what the hell should be in
limine.cfg

boot:///boot/vllinuz-linux doesn't work

We have a PATH    an executable  and COMMANDS,    despite of how simple and how many hundreds of different alterations I have tried it never boots.
In this drive, let's call it /dev/sdb limine is installed and it is showing its colorful boot menu, it is the only boot loader on that disk and system.  Other boot loaders on other systems on other drives can boot this system, nothing wrong with the system's integrity.  No crypt or anything fancy, plain MBR/bios installation on an ext4  partition.  

This entire system is called limine because it served as an experiment to learn how limine works.  In turn, thanks to the chainloading menu option, after several attempts to E and F10, I resort to a different drive's grub and boot the system, to further attempt to re-edit limine.cfg

**Comment by ElectrodeYT** [comment]
You mention ext4... is the `boot/vmlinuz` file on a ext4 partition?

Limine no longer supports ext4 partitions.

**Comment by fungilife** [comment]
> You were kinda being hostile in your original message. And "ranting" doesn't mean that the other party doesn't make sense. It's just that it's an unnecessarily lengthy diatribe.

If you could put half the energy of being ironic to someone who is asking for help in figuring out your software as to writing maybe "a second page with examples" of how this thing works, maybe there would have been no need for a "diatribe" 

Linux x86_64 dos partitioning mbr partition: say sdc1  on drive sdc
/boot/vmlinuz-linux
/boot/limine/limine.cfg
limine installed already and menu appearing

Write an example bootable entry and if this doesn't work we can proceed to debugging what is wrong.  Till then, the documentation is insufficient

**Comment by fungilife** [comment]
> Consider reading [this](https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md)
> 
> Basically, if you want to read a elf file from the boot partition, its `boot:///path/to/elf/file`

consider that the title of the ISSUE is copy paste from that page, is there another?

**Comment by fungilife** [comment]
> You mention ext4... is the `boot/vmlinuz` file on a ext4 partition?
> 
> Limine no longer supports ext4 partitions.

Is there a link to the release that specifically says this, all distro wikis that talk about limine speak of ext4 support when others don't.
And by lack of support does it mean what used to boot with limine and ext4 on MBR will no longer be able to, or just that if it fails don't bother limine devs?  There is a gray area here in the interpretation of the word support!

**Comment by fungilife** [comment]
> You mention ext4... is the `boot/vmlinuz` file on a ext4 partition?
> 
> Limine no longer supports ext4 partitions.

https://github.com/limine-bootloader/limine/blob/trunk/README.md#supported-filesystems

Maybe the devs need to make their mind up instead of going back and forth, is it or is it not supported?

**Comment by ghost** [comment]
> You mention ext4... is the `boot/vmlinuz` file on a ext4 partition?
> 
> Limine no longer supports ext4 partitions.

I didn't see anything official that shows Limine dropped EXT filesystems support. Unless I missed it at a point and time
