### ISSUE TITLE
Problem with locating stage 3 file.

### ISSUE THREAD

**Issue by h4ckee** [Limine-Bootloader/Limine#323]
Hello.
I'm not able to install bootloader on my Thinkpad T430. A have 2 disks /dev/sda and /dev/sdb where root is located. sdb has one GPT partition on it /dev/sdb1. I'm issuing this command:
`limine bios-install /dev/sdb`
and it says install is successfull. After that I'm copying file limine-bios.sys to /boot directory, but after reboot it says that stage 3 file not found! I also tried to put it on /, /limine/ and /boot/limine/ but without any luck. Please check attached screenshot below:
![IMG_20231231_145255](https://github.com/limine-bootloader/limine/assets/14123644/86d52688-7300-481a-a0d2-64c7e5277fc3)

Could you please help to find out the reason?
Best regards,
Sergey.

**Comment by Mintsuki** [comment]
Hi,
This is very likely caused by your root filesystem not being formatted as FAT. As of Limine 6.x, ext2/3/4 support has been dropped, so make sure that your bootloader files are on a FAT partition.

In case that wasn't the problem, feel free to reopen this issue.

**Comment by h4ckee** [comment]
But why ext* filesystems have been dropped? I've moved from syslinux to limine because of ext4 support.

**Comment by Mintsuki** [comment]
https://github.com/limine-bootloader/limine/issues/320
