### ISSUE TITLE
Serial console speed setting missing (or auto discovery)

### ISSUE THREAD

**Issue by rbzchnadm** [Limine-Bootloader/Limine#328]
Currently serial I/O if fixed to 9600 which is annoying if motherboard is configured to anything else. Screen is black until disconnecting serial, changing speed and reconnecting.

Would it be possible to change the SERIAL=yes to SERIAL=<speed> or implement auto discovery ?

You can certainly borrow the code from here :

https://github.com/torvalds/linux/blob/master/arch/x86/boot/early_serial_console.c

**Comment by Mintsuki** [comment]
Actually, we cannot borrow code from there due to licensing differences.

Anyways, I added a `SERIAL_BAUDRATE` config setting in c0fd295c, BIOS only though... For UEFI, changing the baud rate should be done through the motherboard's settings. I hope this suffices.
