### ISSUE TITLE
feature request: limine boot protocol uefi system table request

### ISSUE THREAD

**Issue by SachaTending** [Limine-Bootloader/Limine#329]
it can be helpful for creating uefi kernels using limine boot protocol

**Comment by AshesOfEther** [comment]
[This already exists](https://github.com/limine-bootloader/limine/blob/stable/PROTOCOL.md#efi-system-table-feature)

**Comment by SachaTending** [comment]
> [This already exists](https://github.com/limine-bootloader/limine/blob/stable/PROTOCOL.md#efi-system-table-feature)

oh, thanks
