### ISSUE TITLE
Limine Memory map feature results zero entries.

### ISSUE THREAD

**Issue by programmerlexi** [Limine-Bootloader/Limine#337]
When i have a memory map request in my kernel, the `entry_count` field in the response is zero.

I do the request like this:

```c
static volatile struct limine_memmap_request mmap_request = {
    .id = LIMINE_MEMMAP_REQUEST, .revision = 0, .response = NULL};
```

**Comment by Mintsuki** [comment]
You are casting a pointer to pointer to request to a pointer to request at https://github.com/truemaker/limix/blob/6be19b83c5cc019ab01f1d1447e90face8ec0dd1/kernel/src/main.c#L149

Read: drop the `&` (and perhaps the cast as well since it's useless).

**Comment by programmerlexi** [comment]
I don't even know why i put that cast there.

**Comment by lukflug** [comment]
Because applying the address-of operator causes the expression to have an incompatible type.

So one either understands the root cause of the problem, and removes the address-of operator, or tries to quickly fix the compilation error by adding a cast that fixes nothing.
