### ISSUE TITLE
Cannot boot if i install limine on another disk

### ISSUE THREAD

**Issue by ghost** [Limine-Bootloader/Limine#348]
So i have a dual boot linux setup. I always used grub before and i istalled grub on `/dev/sda` and my linux boot entry was in a partition in `/dev/sdb` but grub still booted my linux setup. But if i install limine on `/dev/sda` and my linux is installed in `/dev/sdb` it shows stage 3 file not found error. When i installed limine on `/dev/sdb` where my linux is installed and booted that disk from bios then my linux setup ran just fine. So i was wondering if i have to install limine on the same disk where linux is installed to make it work.

**Comment by Mintsuki** [comment]
Stage 3 (for BIOS) and `limine.cfg` need to be on the same disk on which Limine is installed; so if you want Limine installed on your `/dev/sda` to boot Linux on your `/dev/sdb`, that is possible, but you still need the stage 3 file (for BIOS) and `limine.cfg` placed on a partition on `/dev/sda`.
