### ISSUE TITLE
Binaries within the repository

### ISSUE THREAD

**Issue by kovmir** [Limine-Bootloader/Limine#355]
Just a question... Why do you keep binaries within the repository rather than attach them as release assets, which can also be automated? It somewhat bothers those willing to contribute, as `git clone ...` is no longer a quick action.

**Comment by Mintsuki** [comment]
I do intend on stopping this practice, but at some point in the past, being able to fetch the latest release assets wasn't so trivial as it is now, hence why the idea of stashing them in their own branch.

I will probably stop doing this once 8.x is out, but until then it will have to stay for backwards compatibility.

Plus it's about 160 MB or so in total, it's not that much, realistically speaking.
