### ISSUE TITLE
Not an x86-64 ELF

### ISSUE THREAD

**Issue by CommanderGL** [limine-bootloader/limine#373]
When I try to load my kernel I get a `Not an x86-64 ELF` error even when booting with `qemu-system-i386`. [Here are my files.](https://github.com/CommanderGL/csos-limine)

**Comment by CommanderGL** [comment]
This is fixed when I switch back to using the multibootv1 protocol. Does the limine protocol only support x86_64?

**Comment by mintsuki** [comment]
Yes, it only supports 64-bit platforms, but not only x86-64, it also supports aarch64 and riscv64 (with possibly more platforms to come in the future).
