### ISSUE TITLE
Specify stack pointer alignment on entry

### ISSUE THREAD

**Issue by adavis628** [Limine-Bootloader/Limine#375]
Currently, the Limine boot protocol doesn't specify the alignment of the stack pointer on entry. On x86_64, the [System V ABI](https://wiki.osdev.org/System_V_ABI#x86-64) requires it to be 16-byte aligned before calling a function. I don't know the required alignments for other architectures, but I'd assume they'd have similar requirements.

**Comment by Mintsuki** [comment]
Hello,

As Limine follows the System V ABI, the stack is 16-aligned + 8 at entry (as the 8 are, as you said, required to hold the return address for the caller, which in Limine's case is set to 0, as per spec).

Likewise for other architectures.
