### ISSUE TITLE
Unable to boot on t460p (and likely other hardware too) starting at limine 7.8.0

### ISSUE THREAD

**Issue by programmerlexi** [Limine-Bootloader/Limine#377]
Limine (starting at version 7.8.0) is unable to boot on my t460p (stock firmware).

I am using the binary branch.

It just flashes the screen and goes back to the UEFI. No menu is shown.

**Comment by programmerlexi** [comment]
This is fixed by #378

**Comment by Mintsuki** [comment]
Fixed by #378
