### ISSUE TITLE
RISC-V port does not respect MAX_PAGING_MODE=Sv39

### ISSUE THREAD

**Issue by robotman2412** [Limine-Bootloader/Limine#380]
Despite this config:
```
TIMEOUT=0

:BadgerOS
    PROTOCOL=limine
    KASLR=no
    KERNEL_PATH=boot:///boot/badger-os.elf
    MAX_PAGING_MODE=Sv39
```
Limine loads BadgerOS with the Sv48 paging mode. BadgerOS supports this but my real hardware does not. To verify my kernel in QEMU, I would like to lock Limine to Sv39 even on systems that support larger paging modes.

**Comment by 48cf** [comment]
MAX_PAGING_MODE is not something you can change through the config. Use the [Paging Mode Request](https://github.com/limine-bootloader/limine/blob/v7.x/PROTOCOL.md#paging-mode-feature) instead.

**Comment by robotman2412** [comment]
> MAX_PAGING_MODE is not something you can change through the config. Use the [Paging Mode Request](https://github.com/limine-bootloader/limine/blob/v7.x/PROTOCOL.md#paging-mode-feature) instead.

In that case, a note should be made about MAX_PAGING_MODE, because `CONFIG.md` states the contrary.

**Comment by 48cf** [comment]
It doesn't..? Where do you see that?

**Comment by 48cf** [comment]
oh wow my bad, yeah i didn't know that

**Comment by 48cf** [comment]
It looks like you still need the Limine request for the config option to take effect, but I might be misreading the source code.

**Comment by robotman2412** [comment]
Fixed same-day, nice
