### ISSUE TITLE
v5 cannot enable A20 line

### ISSUE THREAD

**Issue by bkauler** [Limine-Bootloader/Limine#386]
I know that v5 is no longer supported, but thought I would ask just in case this problem has occurred in a later release and maybe I can backport the fix.

We are stuck on v5 as require ext4 support. 

Puppy Forum member 'tosim' reported getting the error "Cannot enable A20 line".
He has an older computer, HP5800.

I think read that there are different ways of enabling the A20 line. I'm wondering if there has been any modifications to enabling A20 since 5.20231207.1 was released. A long-shot, I know.

**Comment by Mintsuki** [comment]
Hi, these 2 commits may fix the issue.

Additionally, I went ahead and reverted the commit where ext2/3/4 support was dropped, which means it will be back in 7.12.0, albeit with a notice that it is experimental and unmaintained/unsupported upstream. I hope this will do! (Reopen if necessary)

**Comment by bkauler** [comment]
From our point of view, EasyOS, this is very great news! Thank you so much!

I understand the ideology of wanting to keep everything simple and not be bothered with supporting filesystems other than fat.

**Comment by bkauler** [comment]
I have posted about the return of ext4 in the Puppy Forum:

https://forum.puppylinux.com/viewtopic.php?t=12214

**Comment by Mintsuki** [comment]
Nice! Well, 7.12.0 has been released, enjoy. (Also please let me know about that A20 issue, if it's still there)
