### ISSUE TITLE
Is it possible to support "term_font_scale" with floating point numbers?

### ISSUE THREAD

**Issue by Zesko** [Limine-Bootloader/Limine#395]
Limine 8.0.0

I have a monitor with **zoll 27** and 1440p.

defaulf `term_font_scale` is `2x2`, but it is a bit too big and shows **aliased** text in this monitor.

 I tried to set `term_font_scale` to `1x1`, but it is a bit too small without noticing aliasing.

I would like to set `term_font_scale` to `1.5x1.5`, but **floating point numbers** are not supported.

Is that possible to support **floating point numbers**  with the limit exponent 10^-1 like`1.5x1.5`  or `1.2x1.2` for `term_font_scale` ?

Thanks!

**Comment by Mintsuki** [comment]
Hi, this is an issue to open against https://github.com/mintsuki/flanterm
