### ISSUE TITLE
Feature purposal: Show the boot menu when a key is hold

### ISSUE THREAD

**Issue by raphm4044** [Limine-Bootloader/Limine#397]
## How it would work?
If the boot menu is disabled (timeout: 0, and quiet: yes), you can hold a key (example: Shift key) to show the boot menu and other entries. 

## How it is useful?
It could be useful if you don't like the boot menu, but you need sometimes to go on a fallback Linux kernel & initramfs, on a Linux PC.

**Comment by Mintsuki** [comment]
Hi,
you can already achieve this by doing `timeout: 1` and `quiet: yes`. That gives you 1 second of timeout to press a key and reveal the menu, you can use other values for timeout.

**Comment by raphm4044** [comment]
Okay thanks, didn't know that
