### ISSUE TITLE
Overlapping program header loading issue

### ISSUE THREAD

**Issue by ghost** [Limine-Bootloader/Limine#400]
I've followed the docs numerous times, tried to adjust the program headers, etc, etc, and Limine fails with the same "ELF PHDR's 0-2 " or "0-1" failed to load. No it's not the build system because I've switch between clang and GCC. I've even tried to reorder the sections, etc, to no avail. Either the docs are messed up for the ARM platform or Limine itself has an ELF loader bug.

**Comment by Mintsuki** [comment]
Share a minimal, reproducible example of the issue.
