### ISSUE TITLE
Question: How to print in limine based c/rust kernels to screen? Is there any example implementation of flanterm?

### ISSUE THREAD

**Issue by ghost** [Limine-Bootloader/Limine#404]
(Originaly asked on the flanterm repo, also open there)
[main.rs.txt](https://github.com/user-attachments/files/16647735/main.rs.txt)
How do you print text in limine-rust-template using flanterm_bindings crate? Attached is an attempt to do this.
info: first asked in an issue in rust limine template, seemed to be the wrong place to ask according to lylythechosenone. Many thanks for an answer!

**Comment by ghost** [comment]
well, maybe this project helps:https://github.com/ilobilo/limine-terminal

**Comment by Mintsuki** [comment]
Closing this as off topic. Drawing text to the screen is not a Limine related thing. You may want to ask whoever maintains the Flanterm bindings crate.
