### ISSUE TITLE
More Functions to The Limine Protocol

### ISSUE THREAD

**Issue by atlassoftware-cpu** [Limine-Bootloader/Limine#409]
Since the limine protocol provides functions like reading framebuffer info and more, why not include more like UEFI does, like disk functions, Mouse and Keyboard input, a working idt that just requires calling an init function after putting the location of every isr/irq, and more

**Comment by Mintsuki** [comment]
That is very out-of-scope for what the Limine boot protocol is meant to be: kernel executable loading and passing of static info from the firmware to the kernel (with very few exceptions).
