### ISSUE TITLE
Unable to boot windows 7 on NON UEFI American Megatrends Inc. BIOS

### ISSUE THREAD

**Issue by Virexia** [Limine-Bootloader/Limine#412]
Hello.
I have an actual problem.
I'm right now in Arch Linux (btw) and in a **NON UEFI BIOS system.**
before using Limine I used Grub to dualboot Windows 7 and Arch.
I searched multiple solutions but none of them work.
Someone help me.
Arch User.

**Comment by Virexia** [comment]
=(

**Comment by Virexia** [comment]
[https://github.com/Arseniy132/Limine-boot-issue](url)

**Comment by Virexia** [comment]
That link is the .sys and the .conf file

**Comment by kovmir** [comment]
You have provided zero details, nobody will be able to help you.

**Comment by Virexia** [comment]
@kovmir what specifications do you need?

**Comment by afifafifafifafifali** [comment]
A drive can be initialized as MBR or GPT. Windows 7 can be installed as Legacy on a MBR drive or as UEFI on a GPT drive.

**Comment by Virexia** [comment]
@afifafifafifafifali Yes, but I can only use MBR because I have Legacy BIOS as I said before, not UEFI.

**Comment by Mintsuki** [comment]
In order to boot Windows with legacy BIOS you can use the `bios_chainload` protocol as described in the `CONFIG.md` file and chainload the VBR (aka the partition) containing the Windows bootloader.

**Comment by Arseniy132** [comment]
I only have one partition

**Comment by afifafifafifafifali** [comment]
@FER-HUM-LAB-INV  I know. Can you upgrade the BIOS. e.g. SeaBIOS or OVMF which supports UEFI?

**Comment by Virexia** [comment]
@afifafifafifafifali Sorry, but I can't.
I can provide you my motherboard.
ASUS M4A78LT-M

**Comment by Virexia** [comment]
@mintsuki I did not undestand ·_·
