### ISSUE TITLE
Limine showing invalid path when hdd(x:x):/ path format is used.

### ISSUE THREAD

**Issue by edoganii** [Limine-Bootloader/Limine#418]
System Information : 
Limine v8.1.1-1
HP 14 Notebook PC
Arch GNU/Linux (Testing Repo Enabled)
UEFI (CSM Disabled)
EFI v2.3.1 | Vendor: Insyde  | Version: F.31
Intel® Core™ i3-4030U x86_64

![-1_orig](https://github.com/user-attachments/assets/f8912993-5cbe-4013-b11f-8ed954b95d45)

This bug occurred after I tried to normally boot my laptop (I had previously booted into UEFI Shell and Live Arch USB). Limine did not load the wallpaper, and booting into Arch did not work until i used `boot():/` as the path format. Surprisingly, `hdd(x:x):/` path format worked without any problems after I rebooted my laptop (after a successful boot, when I changed `hdd(1:1):/` to `boot():/`). Though this bug happened once, and did not occur again, even when I tried to reproduce it by booting into the UEFI Shell and Arch Live USB again, it's very strange. Also I did not make any change to Kernel images, initramfs or to `limine.conf` whatsoever in the process, except when I changed the path format (`hdd(1:1:/)` to `boot():/`, and that too only to one of the 3 entries of the different version of Linux Kernel) in the Limine menu as mentioned above.

![image](https://github.com/user-attachments/assets/f56bdbcb-f3a3-4bb6-a101-0308580d91e4)

![image](https://github.com/user-attachments/assets/22e5594e-b5ac-4d50-aba1-9e03a7f27e1c)

![image](https://github.com/user-attachments/assets/33b56787-4bbf-4bb7-bdfa-ce0035c7a748)

**Comment by Mintsuki** [comment]
The `hdd(x:x):/` paths rely on the firmware to enumerate disks and then use the order of enumeration to tell which disk is which. It is very conceivable that this firmware, for that specific boot, decided to enumerate disks differently, hence the error. (It would also not be surprising for it to be finnicky given it's an Insyde BIOS).

Try always using `boot():/` or `uuid(xxx):/` as those are *much* more reliable ways to address disks/partitions.

I'll close this as not-a-bug. Feel free to reopen it should something similar happen again while using `boot():/`/`uuid(xxx):/`, though I am pretty confident it won't.
