### ISSUE TITLE
How do I  solve limine.conf issue?

### ISSUE THREAD

**Issue by baponkar** [Limine-Bootloader/Limine#425]
I have `limine.conf` inside of `iso_boot\limine\limine.conf` along with `limine-bios-cd.bin` ,  `limine-uefi-cd.bin` and `limine-bios.sys` file .The `limine.conf` file is look like:
```bash


# Timeout in seconds that Limine will use before automatically booting.
timeout: 60


graphics: yes

interface_resolution: 1366x768

wallpaper: /boot/a.bmp
wallpaper_style: centered

interface_branding: KeblaOS v1.0
interface_branding_colour: 4



# The entry name that will be displayed in the boot menu.
/KeblaOS
    # We use the Limine boot protocol.
    protocol: limine
    

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    kernel_path: boot():/boot/kernel.bin
```

The output look like 
<img width="509" alt="keblaos" src="https://github.com/user-attachments/assets/a2664c6f-a2fa-45fb-bb4c-709e79df3cbb">

Not showing Wallpaper or set proper resolution

**Comment by baponkar** [comment]
I have found solution for wallpaper by changing into  `wallpaper: boot():/boot/a.bmp`

**Comment by baponkar** [comment]
But resolution issue not solved

**Comment by Mintsuki** [comment]
Hi,

The resolution needs to be supported by the machine, which is not a given. Have you tried some other resolution? In any case, you should take it as a hint, given you cannot know in advance whether a machine supports a certain resolution or not.
