### ISSUE TITLE
fallback initramfs entry?

### ISSUE THREAD

**Issue by ghost** [Limine-Bootloader/Limine#427]
I am new to limine but with the help of the Arch Wiki I have successfully setup a main Linux entry. My question is: is it possible to add a fallback initramfs entry like in the GRUB "Advanced options"?And if yes, how? TIA.

**Comment by edoganii** [comment]
Set module_path to fallback-initrd  (which is typically present in ESP)

**Comment by ghost** [comment]
@faiz-x ok, so I add something like`/Arch 6.6 fallback` and leave the cmdline unchanged, just point the module_path to the fallback initramfs? Also, what's the  difference between limine and linux as protocol?

**Comment by edoganii** [comment]
> I add something like`/Arch 6.6 fallback` and leave the cmdline unchanged, just point the module_path to the fallback initramfs?

Yes.



> what's the difference between limine and linux as protocol?

You can read about the limine protocol [here](https://github.com/limine-bootloader/limine/blob/v8.x/PROTOCOL.md)

**Comment by ghost** [comment]
Thank you, I tried to use limine but only linux worked.

**Comment by Mintsuki** [comment]
That is normal. The `limine` boot protocol needs to be supported by the kernel, and Linux only supports the `linux` protocol.
