### ISSUE TITLE
Possibility of a limine-mkrescue type of utility?

### ISSUE THREAD

**Issue by Qix-** [limine-bootloader/limine#44]
During development, `grub-mkrescue` is pretty essential for building quick ISO images for testing in e.g. VMware or Qemu (via `-cdrom`).

Would it be possible to supply a `limine-mkrescue` utility that does something similar?

**Comment by N00byEdge** [comment]
https://github.com/limine-bootloader/limine/blob/master/limine-install.c

**Comment by Qix-** [comment]
@N00byEdge Yep, that installs the bootloader to a pre-existing device or  **raw** image format. It doesn't say anything about generating a standalone rescue ISO given a configuration file and a binary image.

**Comment by N00byEdge** [comment]
Oh sorry, I thought that limine-install was what you were after and that you weren't aware of it. I personally don't see a point of iso images over raw ones, but I suppose that it could be something which has a use case.

**Comment by Qix-** [comment]
Like I said, they're useful for development.

**Comment by Qix-** [comment]
@mintsuki @atiep I think you mis-tagged the issue number as the framebuffer changes in that commit have nothing to do with this issue.

**Comment by Mintsuki** [comment]
Yes, @AtieP wrongly mentioned this issue, sorry.

**Comment by AtieP** [comment]
Sorry

**Comment by Qix-** [comment]
No problem, can we get it reopened perhaps? :)

**Comment by Mintsuki** [comment]
If you want CD-ROM ISO support, you can perhaps open an issue for that specifically ;)

**Comment by Qix-** [comment]
I'm confused, that's mostly what this issue is. Why isn't it being re-opened when it was falsley closed? GRUB has a `mkrescue` command to create quick ISO images, which is... literally exactly that, lol.
