### ISSUE TITLE
UEFI support

### ISSUE THREAD

**Issue by nexos-dev** [Limine-Bootloader/Limine#52]
Hello,
BIOS has been superseded as of 2019. I think it would be a good idea to add a UEFI loader to the repo. I could contribute it in a series of PRs if you would like it.

**Comment by Itay2805** [comment]
UEFI support in Limine is still under consideration and might be added in the future. Until then (#shameless plug) you could use [TomatBoot](https://github.com/TomatOrg/TomatBoot-UEFI) which is a stivale1/stivale2 compliant bootloader (for the most part), and it should be perfectly possible to have a drive with both limine and tomatboot at the same time.

**Comment by nexos-dev** [comment]
Ok, thanks!

**Comment by Mintsuki** [comment]
We agreed that perhaps it is best if Limine stays BIOS-only since TomatBoot exists and it supports the same protocols as Limine does.

**Comment by nexos-dev** [comment]
Ok, makes sense. Thanks!

**Comment by austanss** [comment]
TomatBoot is dead, seems Limine had to fill in it's shoes.

**Comment by nexos-dev** [comment]
Agreed. That makes the most sense to me as it would be easier to just maintain Limine instead of Limine and TomatBoot.
