### ISSUE TITLE
Invalid stivale2 memory map `entries` field

### ISSUE THREAD

**Issue by austanss** [Limine-Bootloader/Limine#82]
**Limine version used**
Release version v2.7.

**Expected behavior**
A proper, correctly-detailed memory map stivale2 structure tag.

**Actual (broken) behaviour**
Incorrect `entries` field.

**To Reproduce**
Use Limine v2.7, create a stivale2 kernel, find the memory map structure tag, and attempt to parse it, and `entries` will be incorrect.

**Stacktrace**
***N/A***

**Additional context**
I was switching to stivale2 and this bug just had to rear its ugly head.

**Comment by Mintsuki** [comment]
How is the `entries` field incorrect, exactly? I cannot reproduce.

**Comment by austanss** [comment]
It is filled with some obscene value.

Source: https://github.com/rizet/micron/tree/waspaloy-alpha/kernel/src/boot

**Comment by austanss** [comment]
My apologies. I was using the framebuffer ID to locate the memory map tag instead of the memmap ID.

Simple mistakes.
