### ISSUE TITLE
Other Binary Formats

### ISSUE THREAD

**Issue by circutrider21** [Limine-Bootloader/Limine#83]
I was wondering if limine had support for other executable format aside from elf, like PE or MachO. It would be quite neat!

**Comment by AtieP** [comment]
Stivale/Stivale2 doesn't allow loading anything other than ELF so you should open an issue or pr there (https://github.com/stivale/stivale)

**Comment by circutrider21** [comment]
Thanks for guiding me, I'll open it there!

**Comment by theoparis** [comment]
Since stivale is archived, is this still something that could be supported? I am interested in this as well, specifically mach-o support.
